name: Main Pipeline
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  REGISTRY: docker.pkg.github.com

jobs:
  build:
    name: Build/Release Container
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Authenticate
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login $REGISTRY -u $GITHUB_ACTOR --password-stdin

      - name: Build
        run: docker build . -t $REGISTRY/enbiso/aws-cli-docker/aws-cli:latest

      - name: Push
        run: docker push $REGISTRY/enbiso/aws-cli-docker/aws-cli:latest
