name: Main Pipeline
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build/Release Container
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Authenticate
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build
        run: docker build . -t ghcr.io/enbiso/aws-cli

      - name: Push
        run: docker push ghcr.io/enbiso/aws-cli
